### PR TITLE
Footer (Slightly Redesigned)

### LINKED ISSUE #238: Incorrect menu icons
**Describe the bug**
(That's not actually bug, but think it have to look another way.) Can't see menu icons correctly. Only 3 of 5 shown correctly but don't look so pretty

**To Reproduce**
Right on the main page.

**Screenshots**
Clipboard02

**Device (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser: Google Chrome
- Version: 78.0.3904.108

**Additional context**
I understand that many of you already know about it, but it have to look at least correctly. Better to use something universal or don't use at all. Students are looking to it and some of them can think, that that's okay, and then use this way to implement the same ;-)

### PR DESCRIPTION
**Pull request by Alxblsk**
Fixes #238.

In addition, in order to decrease the number of custom styles and increase readability, elements in the footer were redesigned.

Desktop:
image

Mobile:
image

### CODE REVIEW

File: client/src/pages/_app.tsx [hunk 1]
```diff
@@ -2,8 +2,8 @@ import * as React from 'react';
 import App from 'next/app';
 import Head from 'next/head';
 
-import '../styles/main.css';
 import 'antd/dist/antd.css';
+import '../styles/main.css';
```
Comment (Alxblsk) [inline client/src/pages/_app.tsx:6]: Custom styles moved to the bottom to overwrite `antd` ones (in case of same selector weights).

File: client/src/components/Footer/FooterLayout.tsx [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+              </Row>
+            </Col>
+            <Col xs={24} sm={12} lg={8}>
+              <Donation />
+            </Col>
+            <Col xs={24} sm={12} lg={16}>
+              <SocialNetworks />
+            </Col>
+            <Col xs={24} sm={12} lg={8}>
+              <small>&copy; The Rolling Scopes {this.getYear()}</small>
```
Comment (Alxblsk) [inline client/src/components/Footer/FooterLayout.tsx:34]: Suppose it should always be a current year.

**Comment by dzmitry-varabei** [comment]
@Alxblsk footer looks great! Thank you!

**Comment by apalchys** [comment]
👍 Great! Feel free to merge
