### PR TITLE
fix: make badge mandatory on the gratitude page

### LINKED ISSUE #649: Make "Badge" mandatory on Feedback page
- Make "Badge" mandatory on Feedback page
- Apply "Thank you" to all feedbacks with empty badge 
- Bonus: Increase default paging size on Heroes page to 20

### PR DESCRIPTION
**Pull request by mikhama**
This fixes #649

### CODE REVIEW

File: server/src/models/feedback.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export class Feedback {
   @Column({ nullable: true })
   comment: string;
 
-  @Column({ nullable: true })
+  @Column({ nullable: true, default: 'Thank_you' })
```
Comment (mikhama) [inline server/src/models/feedback.ts:21]: @apalchys  Can we run the following query after this PR will be merged?
```sql
UPDATE feedback SET "badgeId" = 'Thank_you' WHERE "badgeId" IS NULL;
```

**Review by apalchys — APPROVED** [review]
