### PR TITLE
fix: pagination for stage interview page

### LINKED ISSUE #2596: Pagination Not Working on Stage Interviews Page (js-fe-2024Q4)
I open https://app.rs.school/course/admin/stage-interviews?course=js-fe-2024Q4

Pagination works, but it is impossible to change the number of rows displayed (10, 20, or 100).

Image

### PR DESCRIPTION
**Pull request by karlovich**
**🟢 Add `deploy` label if you want to deploy this Pull Request to staging environment**

#### 🧑‍⚖️ Pull Request Naming Convention

- Title should follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- Do not put issue id in title
- Do not put WIP in title. Use [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) functionality
- Consider to add `area:*` label(s)

* [x] I followed naming convention rules

---

#### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related issue link

- Related Issue #2596
- Closes #2596

#### 💡 Background and solution
BEFORE:
It was not possible to use sizeChanger control with an affect on the page.
sizeChanger control is displayed when items.count >50.

AFTER:
default page size set to ant table pagination,
also displaying of the total items was improved.
So user can change page size and work with interviews page more comfortably.
sizeChanger control is displayed all the time.

image

#### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Database migration is added or not needed
- [x] Documentation is updated/provided or not needed
- [x] Changes are tested locally

### CODE REVIEW

File: client/src/pages/course/admin/stage-interviews.tsx [hunk 1]
```diff
@@ -60,7 +60,13 @@ function Page() {
       </Row>
 
       <Table
-        pagination={{ pageSize: 50 }}
+        pagination={{
+          defaultPageSize: 50,
+          showSizeChanger: true,
+          showTotal: (total, range) => {
+            return `${range[0]}-${range[1]} of ${total} interviews`;
+          },
```
Comment (apalchys) [inline client/src/pages/course/admin/stage-interviews.tsx:68]: Minor but I would inline:

```suggestion
          showTotal: (total, range) => `${range[0]}-${range[1]} of ${total} interviews`,
```

**Review by apalchys — APPROVED** [review]

File: client/src/pages/course/admin/stage-interviews.tsx (hunk 1 above)
Comment (karlovich) [reply client/src/pages/course/admin/stage-interviews.tsx]: nop, fixed in 9a1260b
