### PR TITLE
fix: interviews score displaying

### LINKED ISSUE #1177: Не отображаются баллы за Technical Screening в Schedule
Баллы за Technical Screening 49 / 50 отображаются только в таблице Score, но в Schedule стоит 0 из 50.
изображение
изображение

### LINKED ISSUE #1181: Различаются данные о баллах в Dashboard и Score
**Describe the bug**
Различаются данные о баллах в Dashboard и Score

**To Reproduce**

- в Dashboard 0 / 50 https://app.rs.school/course/student/dashboard?course=js-fe-2021Q3
- в Score 43 https://app.rs.school/course/score?course=js-fe-2021Q3

**Expected behavior**
Ожидаются одинаковые цифры

**Screenshots**
image
image

**Device (please complete the following information):**

- OS: windows 7
- Browser: chrome
- Version: Версия 97.0.4692.99 (Официальная сборка), (64 бит)

### PR DESCRIPTION
**Pull request by mikhama**
#### 🧑‍⚖️ Pull Request Naming Convention

 - Title should follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
 - Do not put issue id in title
 - Do not put WIP in title. Use [Draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) functionality
 - Consider to add `area:*` label(s)

 * [x] I followed naming convention rules

---

#### 🤔 This is a ...
- [ ] New feature
- [x] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related issue link

This fixes #1181 and fixes #1177

#### 💡 Background and solution 

Dashboard:
image

Score:
image

Schedule:
image

Profile:
image

#### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Database migration is added or not needed
- [x] Documentation is updated/provided or not needed
- [x] Changes are tested locally

### CODE REVIEW

File: server/src/repositories/courseTask.repository.ts [hunk 1]
```diff
@@ -69,10 +77,17 @@ export class CourseTaskRepository extends AbstractRepository<CourseTask> {
...
       .leftJoin(TaskResult, 'taskResult', '"taskResult"."courseTaskId" = "courseTask"."id"')
+      .leftJoin(TaskInterviewResult, 'tir', 'tir.courseTaskId = courseTask.id AND "tir"."studentId" = :studentId', {
+        studentId: student?.id,
+      })
       .leftJoin(TaskResult, 'tr', '"tr"."courseTaskId" = "courseTask"."id" AND "tr"."studentId" = :studentId', {
         studentId: student?.id,
       })
-      .addSelect('tr.score', 'score')
+      .leftJoin(StageInterview, 'si', '"si"."studentId" = :studentId AND "si"."courseTaskId" = "courseTask"."id"', {
+        studentId: student?.id,
```
Comment (aaliakseyenka) [inline server/src/repositories/courseTask.repository.ts:87]: this optional chaining is misleading: if there is no user should we execute the query for tasks? seems no. probably better to add additional check above and not use optional chaining here.
